---
- name: set timezone Europe/Prague
  timezone: name=Europe/Prague

- name: set locales
  locale_gen: name=cs_CZ.UTF-8 state=present

- name: Basic programs
  apt: pkg={{ item }}
  with_items:
    - sudo
    - vim
    - htop
    - curl
    - zsh
    - git
    - whois
    - pwgen
    - dirmngr
    - tmux
    - aptitude
    - gpgv2
    - telnet

- name: Adduser lajbor
  user: name=lajbor groups=sudo password="{{ lookup('password', '~/.ansible/credentials/' + ansible_host + '/user length=8') }}"

